Fan:
  type: integer
  constraints:
    min: 0
    max: 30

Refrigerator:
  type: float
  constraints:
    min: 10.0
    max: 30.0

AirConditioner:
  type: float
  constraints:
    min: 0.0
    max: 7.0

Television:
  type: float
  constraints:
    min: 0.0
    max: 30.0

Month:
  type: integer
  constraints:
    min: 1
    max: 12

MonthlyHours:
  type: integer
  constraints:
    min: 100
    max: 1000

TariffRate:
  type: float
  constraints:
    min: 5.40
    max: 10.30

TotalApplianceHours:
  type: float
  constraints:
    min: 20.0
    max: 90.0

City:
  type: string
  constraints:
    enum:
      - Hyderabad
      - Vadodara
      - Shimla
      - Mumbai
      - Ratnagiri
      - New Delhi
      - Dahej
      - Ahmedabad
      - Noida
      - Nagpur
      - Chennai
      - Faridabad
      - Kolkata
      - Pune
      - Gurgaon
      - Navi Mumbai

Company:
  type: string
  constraints:
    enum:
      - Tata Power Company Ltd.
      - NHPC
      - Jyoti Structure
      - Power Grid Corp
      - Ratnagiri Gas and Power Pvt. Ltd. (RGPPL)
      - Adani Power Ltd.
      - Kalpataru Power
      - Orient Green
      - Sterlite Power Transmission Ltd
      - Neueon Towers / Sujana Towers Ltd.
      - KEC International
      - Indowind Energy
      - Unitech Power Transmission Ltd.
      - Bonfiglioli Transmission Pvt. Ltd
      - SJVN Ltd.
      - Maha Transco – Maharashtra State Electricity Transmission Co, Ltd.  # Add this
      - L&T Transmission & Distribution
      - Guj Ind Power
      - Torrent Power Ltd.
      - Reliance Energy
      - GE T&D India Limited
      - NTPC Pvt. Ltd.
      - KEC International
      - Optibelt Power Transmission India Private Limited
      - CESC
      - Ringfeder Power Transmission India Pvt. Ltd.
      - JSW Energy Ltd.
      - Sunil Hitech Eng
      - Toshiba Transmission & Distribution Systems (India) Pvt. Ltd.  
      - Kalpataru Power
      - Jaiprakash Power
      - Bonfiglioli Transmission Pvt. Ltd.
      - Optibelt Power Transmission India Private Limited
      - TransRail Lighting
      - NLC India 
      - Reliance Power 

season:
  type: string
  constraints:
    enum:
      - Winter
      - Summer
      - Monsoon

UsageCategory:
  type: string
  constraints:
    enum:
      - High
      - Medium
      - Low

ElectricityBill:
  type: float
  constraints:
    min: 500.0
    max: 15000.0