
artifacts_root: artifacts

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_validation/validated_data.parquet
  random_state: 42
  target_col: 'converted'
  numerical_cols:
  

  categorical_cols:    - 
